database:
  name: sampledb
  user: "my-user"
  password: "my-password"
eap8:
  build:
    uri: https://github.com/jboss-eap-up-and-running/eap8-with-postgres
    env:
      - name: POSTGRESQL_DRIVER_VERSION
        value: '42.7.3'
  deploy:
    env:
      # Env vars to connect to PostgreSQL DB
      - name: POSTGRESQL_DATABASE
        valueFrom:
          secretKeyRef:
            key: database-name
            name: postgresql
      - name: POSTGRESQL_USER
        valueFrom:
          secretKeyRef:
            key: database-user
            name: postgresql
      - name: POSTGRESQL_PASSWORD
        valueFrom:
          secretKeyRef:
            key: database-password
            name: postgresql
      - name: POSTGRESQL_DATASOURCE
        value: qs-ds
      - name: POSTGRESQL_SERVICE_HOST
        value: postgresql